### ISSUE TITLE
是否每个用浏览器登录这个网站的计算机都成为了一个IPFS节点

### ISSUE THREAD

**Issue by WXXXXW** [UnsignedInt8/Forever#1]
还是只有服务器是IPFS网络中的节点，我在我的服务器上部署了一下这个系统，好像后台没有数据库啊

**Comment by UnsignedInt8** [comment]
是的，只有前端。通过webrtc连接到IPFS网络

**Comment by WXXXXW** [comment]
我想在后台添加一个数据库的话，想请问您客户端与服务器交互的那段代码写在哪个文件里？

**Comment by UnsignedInt8** [comment]
这个是没有服务器交互的，仅仅是用的IPFS提供的接口

如果一定要和私有服务器交互的话，/src/p2p/FileSystem.ts 可能会有帮助

**Comment by WXXXXW** [comment]
好的，感谢不倦解答，还想请教您：我想搭建一个后台数据库，来管理所有客户端上传的数据的一些简要信息，比如对应的文件名和哈希码等等，您建议应该怎样操作呢？还有我之前没有接触过typescript，有没有推荐的一些教程啊

**Comment by WXXXXW** [comment]
方便的话，可以给下您的联系方式吗？便于向您请教，万分感激，我的QQ:1305078733

**Comment by UnsignedInt8** [comment]
不用QQ，用telegram @unsignedint8

**Comment by UnsignedInt8** [comment]
可以自己写后端管理用户数据，没问题
